name: CanliDizi FirePlayer Extractor

on:
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Paketleri kur
        run: |
          pip install selenium webdriver-manager

      - name: Chromium kur
        run: |
          sudo apt-get update
          sudo apt-get install -y chromium-browser chromium-chromedriver

      - name: Çalıştır
        run: |
          python canlidizi.py
