name: HdFilmCehennemi Bot

on:
  push:
    branches: [ main ]
  schedule:
    - cron: '0 12 * * *' # Her gün öğlen 12'de otomatik çalışır
  workflow_dispatch: # Manuel başlatma butonu ekler

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Repo Kontrol
        uses: actions/checkout@v3

      - name: Python Kur
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Chrome Kur
        run: |
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable

      - name: Kütüphaneleri Yükle
        run: |
          pip install selenium webdriver-manager beautifulsoup4 requests

      - name: Botu Çalıştır
        run: python ceho.py
